### ISSUE TITLE
name 'wx' is not defined

### ISSUE THREAD

**Issue by till-schertenleib** [diffpy/diffpy.pdfgui#106]
Error message appears when typing in constraints tab:  name 'wx' is not defined.

I am getting this error message whenever I want to type-in @Number variables in the constraints tap of the phase (cif file)
I installed pdfgui2 using conda-forge in a python=3.9 environment. The problem seems to be with wxpython. It installed wxpython 4. but I am not sure if it actually requires wxpthon 3 - but this seems to be only available for older python versions (python 2)

Any idea how to fix that?

Cheers,

Till

![error_message](https://github.com/diffpy/diffpy.pdfgui/assets/112166086/339da4c4-ae36-4d11-9451-f8a6ae86347b)

![wxpython](https://github.com/diffpy/diffpy.pdfgui/assets/112166086/42d017ba-4cdb-487b-a451-18c096b781cf)

**Comment by sbillinge** [comment]
cross-ref with #144   These may fix each other but check with Till after the fix.
