### ISSUE TITLE
Plot issue when try to plot the fitting in PDFGui

### ISSUE THREAD

**Issue by michael2124** [diffpy/diffpy.pdfgui#114]
Hi everyone,

When I try to plot the fitting in PDFGui, I found the below issues, anyone can tell me why? The machine is based on a Mac OS silicon M1 chip.

<img width="1055" alt="Screenshot 2024-06-28 at 10 37 55" src="https://github.com/diffpy/diffpy.pdfgui/assets/165403977/5b8f6f3b-3d30-431f-84c5-8f8ace4eabc9">

Very looking forwards to your answer.

Best regards,
Michael

**Comment by Joweke** [comment]
Did you find a solution? I have a very similar error. We both are on Apple Silicon, and I don't think that's a coincidence.

**Comment by michael2124** [comment]
> Did you find a solution? I have a very similar error. We both are on Apple Silicon, and I don't think that's a coincidence.

Hi Joweke,
This issue has been solved. please check the discussion: https://groups.google.com/g/diffpy-users/c/Mxg9fI5DCiQ
Good luck.

Best regards,
Michael

**Comment by michael2124** [comment]
The issue has been solved. So it is closed now.
