### ISSUE TITLE
file dialog filtering on Mac OS X

### ISSUE THREAD

**Issue by pavoljuhas** [diffpy/diffpy.pdfgui#16]
The "Open Project" dialog should only show the `*.ddp` files, but it shows all files on Mac.
Explore if there is a workaround.  Apply similar fix for the "Load Phase" and "Load Dataset" dialogs.

**Comment by dragonyanglong** [comment]
@pavoljuhas , could you give us a brief description of which files are relevant with this issue? Thx.

**Comment by dragonyanglong** [comment]
we find a relevant function `onOpen` in mainframe.py file, we think changing the line below may solve the issue, but we are not sure yet. 
`matchstring = "PDFgui project files (*.ddp)|*.ddp|All Files|*"`

Another question, is this problem only exist on Mac OS X or exist on all systems (Win, Linux, and Mac OS X)? Thx

**Comment by pavoljuhas** [comment]
Yes, it is call to [wx.FileDialog](https://github.com/diffpy/diffpy.pdfgui/blob/ea7837d83ed5b05db7908829c6bcd28697f6d33c/src/diffpy/pdfgui/gui/mainframe.py#L2130-L2131) which opens the file dialog.

The file-extension filtering works OK on Linux:
![screen shot 2017-06-20 at 4 29 17 pm](https://user-images.githubusercontent.com/1915760/27354737-9761d846-55d6-11e7-8ba5-5e531b90df80.png)

but on Mac it shows all files:
![screen shot 2017-06-20 at 4 13 05 pm](https://user-images.githubusercontent.com/1915760/27354758-a3fe7a96-55d6-11e7-8160-35fb29d80b20.png)

I am not sure about Windows - do you have access to a Windows box or VM to try?

I'd suggest to Google about list filtering in wx.FileDialog on Mac.  Another possibility is that PDFgui was written with wxpython 2.8, but now that GUI toolkit is version 3.0.  I'd check the wx.FileDialog docs to make sure the filter pattern is used correctly.

**Comment by pavoljuhas** [comment]
BTW, I'd suggest to install pdfgui in a development mode to test your changes.  
Here are my previous notes how to do so: https://github.com/diffpy/diffpy.pdfgui/issues/15#issuecomment-300208743 and https://github.com/diffpy/diffpy.pdfgui/issues/15#issuecomment-305721133.
You can also ask Tim if you run into any problems with that.

**Comment by dragonyanglong** [comment]
The pdfgui in development mode is installed succesfully, thanks for the instruction.

When we change 
`matchstring = "PDFgui project files (*.ddp)|*.ddp|All Files|*"`
into (we follow the format for the filter in wx.FileDialog doc: https://wxpython.org/docs/api/wx.FileDialog-class.html)
`matchstring = "PDFgui project files (*.ddp)|*.ddp"`

The result is as below:
![screen shot 2017-06-20 at 5 22 31 pm](https://user-images.githubusercontent.com/16789768/27356594-11d5dd74-55dd-11e7-8ecf-7706511a7ab0.png)

Only ddp files can be chosen. Would it be your expectation? Or you want it the same as on Linux (only ddp files are shown). 

We don't have access to Windows. We can try it on Win as well later.

**Comment by pavoljuhas** [comment]
I see - wx.FileDialog in the end calls an OS-native GUI library and it seems that wildcard filtering works differently on Mac than on Linux.  On Linux multiple wildcards produce a drop-down menu to choose which one should be applied.  On Mac all wildcards are applied and OR-ed and then only the maching files are *enabled* (although all files are displayed).  Thus if there is an `All Files|*` wildcard Mac filedialog would enable all files regardless of other wildcards.

I think it is OK to change the wildcard for opening PDFgui project to `*.ddp`.  It is unlikely user would rename PDFgui project file to some other extension and then wanted to open it.  In short - let's change that matchstring as you suggest.

However having a drop-down menu with supported wildcards would be useful for loading datasets, because they usually end with `.gr`, but can have any extension.

Can you post a question to https://groups.google.com/forum/#!forum/wx-users if there is a way on Mac OS X to show drop down menu with several wildcards in wx.FileDialog?
You can run that post by me if needed.

**Comment by dragonyanglong** [comment]
I see, thanks for the explanation. I have posted the question, and now waits for the approval, then it will appear in the google group.

**Comment by pavoljuhas** [comment]
Sounds great.

**Comment by pavoljuhas** [comment]
There does not seem much response on [wx-users](https://groups.google.com/d/msg/wx-users/H86wvaNVKx0/BVmUGRJAAAAJ).  Let's just change the wildcard for opening project files.
@dragonyanglong - can you submit a PR?

**Comment by dragonyanglong** [comment]
just submited PR. Is everthing fine?
