### ISSUE TITLE
development mode file dir wrong

### ISSUE THREAD

**Issue by Tieqiong** [diffpy/diffpy.pdfgui#162]
**Description**
Tests not running properly when installed in developer mode.

**Reproduce**
run `pip install -e .` then run tests like `python -m diffpy.pdfgui.tests.run` it will show errors.

**Trace back**
The problem is possibly located at `diffpy/pdfgui/gui/pdfguiglobals.py` and maybe other files.
See line 43:51.

**Comment by bobleesj** [comment]
Fixed with cookiecutting

**Comment by bobleesj** [comment]
@Tieqiong I think this has been resolved in #170  please double check

**Comment by bobleesj** [comment]
Work using both `pip install .` and `pip install -e .`

**Comment by bobleesj** [comment]
@Tieqiong could you please close this?
