### ISSUE TITLE
windows installer for most recent pdfGUI release

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.pdfgui#17]
We at least need a Windows 64 bit, and ideally also a 32 bit installer for the latest stable PDFgui release.

These installers don't have to be made as frequently as now patches and bugfixes make their way into the conda version, but shouldn't lag too far behind.

**Comment by dragonyanglong** [comment]
One possible solution: pyinstaller    
cons: .exe file would be extremely large.

**Comment by sbillinge** [comment]
closing as we are using conda-forge now.  Mostly we are not getting complaints
