### ISSUE TITLE
Fix the workaround for removing test depreciation warning in PR#170

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.pdfgui#176]
History:

- Tieqiong identified the tests failing in dev mode: https://github.com/diffpy/diffpy.pdfgui/issues/162
- Tieqiong found a workaround with a new merged PR: https://github.com/diffpy/diffpy.pdfgui/pull/170/files

Improvement:

- The merged PR fixes depreciation warning and runs tests.
- It was discussed during a meeting (@sbillinge) that we want to clean up (remove files) and reduce technical debt.

**Comment by sbillinge** [comment]
I think we just need to bring everything up to cookiecutter standards for running tests here?

**Comment by bobleesj** [comment]
@bobleesj cookiecut this

**Comment by bobleesj** [comment]
@Tieqiong can we close this? The major change seems to be migrating from `pkg_resources` to `importlib.resources` to parse values such as version, etc. Are there any remaining things to check or do?

**Comment by Tieqiong** [comment]
@bobleesj This issue is good to go as long as both `pip install .` and `pip install -e .` both pass pytest

**Comment by bobleesj** [comment]
> @bobleesj This issue is good to go as long as `pip install .` and `pip install -e .` both pass pytest

Yup works. @sbillinge could you please close this issue?

**Comment by sbillinge** [comment]
Closed as fixed
