### ISSUE TITLE
check whether `asunicode(s)` is actually needed

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.pdfgui#188]
when dropping py2 support, do we still even need `asunicode()`?  Check where it is used and whether it can be removed.

**Comment by Tieqiong** [comment]
@sbillinge this method is used for load and save binary files (mainly zipped project file). I think we can remove it and simply use `.decode("utf-8")`.

**Comment by bobleesj** [comment]
@Tieqiong will take care of it for v3.1.0

**Comment by sbillinge** [comment]
we discussed and decided that the test was not really needed so am closing this.
