### ISSUE TITLE
check that documentation works in gui

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.pdfgui#197]
3.1.0rc4 is not finding the documentation in python 3.11 env on windows (simon).   

Expected:
selecting documentation under help resolves to online documentation

observed:
a browser opens but opens to some default page for the browser in question (msn news page for Simon)

**Comment by Tieqiong** [comment]
@sbillinge I think this is the same as #172

**Comment by sbillinge** [comment]
closing as same as #172
