### ISSUE TITLE
Toolbars do not appear in plot windows OSX running in 64-bit mode 

### ISSUE THREAD

**Issue by cfarrow** [diffpy/diffpy.pdfgui#2]
See discussion in #1.

![image](https://f.cloud.github.com/assets/842366/1682830/531ba06e-5db3-11e3-856b-658932858377.png)

**Comment by pavoljuhas** [comment]
Fixed by 0da29cd4d65bef55abf5eec851b46ebf9c7ef39c...cb4c8a16cc41c7f4426442e3df7ec865489f1a5e.  Looks OK on Mac OS X and wxPython 3.0.0.0.

**Comment by pavoljuhas** [comment]
DONE.
