### ISSUE TITLE
remove Print tool from plot toolbar

### ISSUE THREAD

**Issue by pavoljuhas** [diffpy/diffpy.pdfgui#20]
The print-icon on plot window toolbar shows exception in the terminal:

```
AttributeError: 'FigureCanvasWxAgg' object has no attribute 'Printer_Print'
```

This is because matplotlib 1.3 dropped print support for wx backend matplotlib/matplotlib@84ffb605d4dd06de0dc7eebb2605a35596c9e092.

Let's remove that dysfunctional icon as well.

**Comment by chiahaoliu** [comment]
I can take this

**Comment by pavoljuhas** [comment]
Thank you, please hold on a bit with making a new branch until I merge #15.

**Comment by pavoljuhas** [comment]
@chiahaoliu - all yours.  I have fixed the icon path issue for the development mode so it should not be necessary to create the `icons` symbolic link anymore.
