### ISSUE TITLE
macOS Python 3.9-3.12 installation problem due to older version of wxpython on conda-forge

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.pdfgui#217]
Following the instruction: https://www.diffpy.org/products/pdfgui.html

```
conda create --name=pdfgui2 python=3.9
conda activate pdfgui2 # Install 3.0.5
conda install -c conda-forge diffpy.pdfgui
```

I get the following error message:
                                                                                                                                                            
```
(pdfgui2) macbook@Macbook-Air-327 ~ % pdfgui
Traceback (most recent call last):
  File "/Users/macbook/miniconda3/envs/pdfgui2/bin/pdfgui", line 11, in <module>
    sys.exit(main())
  File "/Users/macbook/miniconda3/envs/pdfgui2/lib/python3.9/site-packages/diffpy/pdfgui/applications/pdfgui.py", line 117, in main
    import diffpy.pdfgui.gui.main as guimain
  File "/Users/macbook/miniconda3/envs/pdfgui2/lib/python3.9/site-packages/diffpy/pdfgui/gui/main.py", line 19, in <module>
    import wx
  File "/Users/macbook/miniconda3/envs/pdfgui2/lib/python3.9/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/Users/macbook/miniconda3/envs/pdfgui2/lib/python3.9/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: dlopen(/Users/macbook/miniconda3/envs/pdfgui2/lib/python3.9/site-packages/wx/_core.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libwx_osx_cocoau_core-3.2.0.2.3.dylib
  Referenced from: <DFCA0D82-07A5-319D-A434-ECCDA751BA46> /Users/macbook/miniconda3/envs/pdfgui2/lib/python3.9/site-packages/wx/_core.cpython-39-darwin.so
  Reason: tried: '/Users/macbook/miniconda3/envs/pdfgui2/lib/python3.9/site-packages/wx/../../../libwx_osx_cocoau_core-3.2.0.2.3.dylib' (no such file), '/Users/macbook/miniconda3/envs/pdfgui2/lib/python3.9/site-packages/wx/../../../libwx_osx_cocoau_core-3.2.0.2.3.dylib' (no such file), '/Users/macbook/miniconda3/envs/pdfgui2/bin/../lib/libwx_osx_cocoau_core-3.2.0.2.3.dylib' (no such file), '/Users/macbook/miniconda3/envs/pdfgui2/bin/../lib/libwx_osx_cocoau_core-3.2.0.2.3.dylib' (no such file), '/usr/local/lib/libwx_osx_cocoau_core-3.2.0.2.3.dylib' (no such file), '/usr/lib/libwx_osx_cocoau_core-3.2.0.2.3.dylib' (no such file, not in dyld cache)
```

This error message is also reproduced for Python 3.12 when I follow the standard:

```
conda create -n pdfgui_env python=3.12
conda activate pdfgui_env
conda install --file requirements/run.txt --file requirements/test.txt
pip install --no-deps .
pytest
```

One way to fix the problem is moving `wxpython` from `run.txt` to `pip.txt` and do the following:

```
conda create -n pdfgui_env python=3.12
conda activate pdfgui_env
conda install --file requirements/run.txt --file requirements/test.txt
pip install -r requirements/pip.txt
pip install --no-deps .
pytest
```

We need to understand why the error occurs in the first place.

**Comment by Tieqiong** [comment]
@bobleesj pdfgui don't have arm build on conda-forge, so do pdffit2. So when testing with arm Mac make sure you get the latest pdffit2 via pypi.

The wxpython error is from its latest conda-forge release: wxpython=4.2.1=py312h10d1a2f_6. If you instead install a previous release (for example `conda install wxpython=4.2.1=py312h4fd8812_5`) the error goes away. Same idea apply to pip install wxpython.

One thing to notice is that we include the entire `run.txt` as dependencies in pyproject.toml. This could be problematic because pypi don't have `matplotlib-base` (it only exists for conda-forge). So potentially when people install pdfgui from pypi there might be dependency installing issues.

**Comment by bobleesj** [comment]
Thanks Tieqiong. Very helpful. 

Just to note the error also occurs for non arm64 macOS as well. This seems to be a very high priority task. 

The problem is resolved with the latest 4.2.2 wxpython on pypi but it is not available on conda forge yet.

I will suggest a solution regarding matplotlib-base and the rest.

**Comment by bobleesj** [comment]
Update the following works using build 5, 4.2.1. wxpython (macOS Intel)

```
conda create -n pdfgui_env python=3.12
conda install --file requirements/run.txt. # do not include wxpython
conda install wxpython=4.2.1=py312h4fd8812_5   # the last few numbers depends on OS
pip install pytest
pytest
```

Installed dependencies:
 
```
  diffpy.pdffit2     conda-forge/osx-64::diffpy.pdffit2-1.4.3-py312he44c6bd_8 
  diffpy.structure   conda-forge/noarch::diffpy.structure-3.2.2rc0-pyhd8ed1ab_0 
  diffpy.utils       conda-forge/noarch::diffpy.utils-3.4.2-pyhd8ed1ab_1 
  numpy              conda-forge/osx-64::numpy-2.1.1-py312he4d506f_0 
  wxpython           conda-forge/osx-64::wxpython-4.2.1-py312hba984fc_5 

```=========== 58 passed, 3 warnings in 29.79s ===========```
```

**Comment by bobleesj** [comment]
Closing - today 4.2.2 is released via conda-forge as of now, `conda install wxpython` automatically installs 4.2.2 (the latest version released a few weeks ago). Tested.
