### ISSUE TITLE
update sources for wxpython4

### ISSUE THREAD

**Issue by pavoljuhas** [diffpy/diffpy.pdfgui#33]
Problem: After update to conda=4.7.5 the earliest version of wxpython in conda channels is 4.0.1.
wxpython 3 can be installed manually with
```
conda install -c anaconda wxpython=3
```
but this is a last-resort workaround and is not viable longer term.

Solution: Update PDFgui sources to work with wxpython 4.

**Comment by pavoljuhas** [comment]
@dragonyanglong - can you please take on this one?
cc: @sbillinge

**Comment by dragonyanglong** [comment]
Sure!

**Comment by pavoljuhas** [comment]
relevant blog post from Anaconda -
https://www.anaconda.com/why-we-removed-the-free-channel-in-conda-4-7/

TLDR - old packages can be re-enabled with a penalty of slower installation
```
conda config --set restore_free_channel true
```
