### ISSUE TITLE
fix installation with pip if possible

### ISSUE THREAD

**Issue by pavoljuhas** [diffpy/diffpy.pdfgui#37]
icons are not installed to correct paths

**Comment by bobleesj** [comment]
@bobleesj the icons folder should be available in v3.1.0 since we use `graft src` in MANIFEST.in. Double-check this after re-cookiecutting and pypi release.

**Comment by bobleesj** [comment]
Resolved - `diffpy_pdfgui-3.1.0rc4` with the new cookiecutter.

**Comment by bobleesj** [comment]
@sbillinge could you please close this?  I checked manually from the sdist that `icons` are distributed.

**Comment by sbillinge** [comment]
Thanks @bobleesj
