### ISSUE TITLE
py3 pickel encoding incompatible

### ISSUE THREAD

**Issue by dragonyanglong** [diffpy/diffpy.pdfgui#44]
In `diffpy.pdfgui/src/diffpy/pdfgui/gui/fittree.py", line 565`, py3 cannot combine bytes and str directly together. `cdatastring = "pdfgui_cliboard=" + cdatastring`

I tried to add .encode() after the str then combien two bytes together, ie. `cdatastring = "pdfgui_cliboard=".encode() + cdatastring`. But a new bug appears:

```
diffpy/pdfgui/gui/fittree.py", line 565, in CopyBranch
    textdata = wx.TextDataObject(cdatastring)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 16: invalid start byte
```

It may be due to the pickel problem.

**Comment by dragonyanglong** [comment]
Hi @tienhungvuong, can you help take a look on this py3 pickel issue, which results into some encode/decode problem that I am not familiar with, we can discuss together. I bet there should be some quick fixes if we can spend more time on googling for answers.

**Comment by tienhungvuong** [comment]
Yes I'll take a look at this!

**Comment by dragonyanglong** [comment]
Fixed.
