### ISSUE TITLE
Temperature series multiple data file import error

### ISSUE THREAD

**Issue by LalitYadav07** [diffpy/diffpy.pdfgui#98]
The new pdfgui version throws up error when importing files in temperature series micro:

Traceback (most recent call last):
  File "C:\Users\lalit\anaconda3\envs\pdfgui2\lib\site-packages\diffpy\pdfgui\gui\errorwrapper.py", line 62, in _f
    return func(*args, **kwargs)
  File "C:\Users\lalit\anaconda3\envs\pdfgui2\lib\site-packages\diffpy\pdfgui\gui\temperatureseriespanel.py", line 286, in fillList
    index = self.listCtrlFiles.InsertItem(sys.maxsize, str(temperature))
wx._core.wxAssertionError: C++ assertion "info.m_itemId != -1" failed at ..\..\src\msw\listctrl.cpp(1981) in wxListCtrl::InsertItem(): Item ID must be set.

**Comment by dragonyanglong** [comment]
Hi @LalitYadav07 , we have fixed this issue. You can run `conda install -c conda-forge diffpy.pdfgui` again in the same conda environment to update the pdfgui version into v2.0.2.

**Comment by dragonyanglong** [comment]
Hi @LalitYadav07 , thanks for reporting the issue. This is due to different system setting across windows and other OS. We have fixed it and updated the version into v2.0.3. Please try running `conda install -c conda-forge diffpy.pdfgui` in the same conda environment to update your pdfgui.

**Comment by dragonyanglong** [comment]
it may take some while to be updated.
